development:
  adapter: postgresql
  database: tei_visualization
  pool: 5
  min_messages: warning
  allow_concurrency: true
  timeout: 5000

test:
  adapter: postgresql
  database: tei_visualization_test
  pool: 5
  min_messages: warning
  allow_concurrency: true
  timeout: 5000

production:
  adapter: postgresql
  database: tei_visualization
  pool: 5
  min_messages: warning
  allow_concurrency: true
  timeout: 5000
